using System;
using System.Collections.Generic;

namespace Querier.Api.Infrastructure.Database.Templates
{
    public class TemplateProperty
    {
        public string Name { get; set; }
        public string CSName { get; set; }
        public string CSType { get; set; }
        public bool IsKey { get; set; }
        public bool IsRequired { get; set; }
        public bool IsAutoGenerated { get; set; }
        public string SqlParameterType { get; set; }
        public bool IsForeignKey { get; set; }
        public bool IsEntityKey => IsKey && !IsForeignKey;
    }
} 