//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Querier.Api.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Querier.Api.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&apos;en&apos;&gt;
        ///    &lt;head&gt;
        ///        &lt;meta charset=&apos;UTF-8&apos;&gt;
        ///        &lt;meta http-equiv=&apos;X-UA-Compatible&apos; content=&apos;IE=edge&apos;&gt;
        ///        &lt;meta name=&apos;viewport&apos; content=&apos;width=device-width, initial-scale=1.0&apos;&gt;
        ///        &lt;title&gt;Document&lt;/title&gt;
        ///        &lt;style&gt;
        ///            *{
        ///                box-sizing: border-box;
        ///                font-family: sans-serif;
        ///            }
        ///            body{
        ///                margin: 0;
        ///                display: flex;
        ///                flex-direction: column;
        ///       [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string EmailConfirmation_de {
            get {
                return ResourceManager.GetString("EmailConfirmation.de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&apos;en&apos;&gt;
        ///    &lt;head&gt;
        ///        &lt;meta charset=&apos;UTF-8&apos;&gt;
        ///        &lt;meta http-equiv=&apos;X-UA-Compatible&apos; content=&apos;IE=edge&apos;&gt;
        ///        &lt;meta name=&apos;viewport&apos; content=&apos;width=device-width, initial-scale=1.0&apos;&gt;
        ///        &lt;title&gt;Document&lt;/title&gt;
        ///        &lt;style&gt;
        ///            *{
        ///                box-sizing: border-box;
        ///                font-family: sans-serif;
        ///            }
        ///            body{
        ///                margin: 0;
        ///                display: flex;
        ///                flex-direction: column;
        ///       [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string EmailConfirmation_en {
            get {
                return ResourceManager.GetString("EmailConfirmation.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&apos;en&apos;&gt;
        ///    &lt;head&gt;
        ///        &lt;meta charset=&apos;UTF-8&apos;&gt;
        ///        &lt;meta http-equiv=&apos;X-UA-Compatible&apos; content=&apos;IE=edge&apos;&gt;
        ///        &lt;meta name=&apos;viewport&apos; content=&apos;width=device-width, initial-scale=1.0&apos;&gt;
        ///        &lt;title&gt;Document&lt;/title&gt;
        ///        &lt;style&gt;
        ///            *{
        ///                box-sizing: border-box;
        ///                font-family: sans-serif;
        ///            }
        ///            body{
        ///                margin: 0;
        ///                display: flex;
        ///                flex-direction: column;
        ///       [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string EmailConfirmation_fr {
            get {
                return ResourceManager.GetString("EmailConfirmation.fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&apos;en&apos;&gt;
        ///    &lt;head&gt;
        ///        &lt;meta charset=&apos;UTF-8&apos;&gt;
        ///        &lt;meta http-equiv=&apos;X-UA-Compatible&apos; content=&apos;IE=edge&apos;&gt;
        ///        &lt;meta name=&apos;viewport&apos; content=&apos;width=device-width, initial-scale=1.0&apos;&gt;
        ///        &lt;title&gt;Document&lt;/title&gt;
        ///        &lt;style&gt;
        ///            *{
        ///                box-sizing: border-box;
        ///                font-family: sans-serif;
        ///            }
        ///            body{
        ///                margin: 0;
        ///                display: flex;
        ///                flex-direction: column;
        ///       [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string EmailResetPassword_de {
            get {
                return ResourceManager.GetString("EmailResetPassword.de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&apos;en&apos;&gt;
        ///    &lt;head&gt;
        ///        &lt;meta charset=&apos;UTF-8&apos;&gt;
        ///        &lt;meta http-equiv=&apos;X-UA-Compatible&apos; content=&apos;IE=edge&apos;&gt;
        ///        &lt;meta name=&apos;viewport&apos; content=&apos;width=device-width, initial-scale=1.0&apos;&gt;
        ///        &lt;title&gt;Document&lt;/title&gt;
        ///        &lt;style&gt;
        ///            *{
        ///                box-sizing: border-box;
        ///                font-family: sans-serif;
        ///            }
        ///            body{
        ///                margin: 0;
        ///                display: flex;
        ///                flex-direction: column;
        ///       [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string EmailResetPassword_en {
            get {
                return ResourceManager.GetString("EmailResetPassword.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&apos;en&apos;&gt;
        ///    &lt;head&gt;
        ///        &lt;meta charset=&apos;UTF-8&apos;&gt;
        ///        &lt;meta http-equiv=&apos;X-UA-Compatible&apos; content=&apos;IE=edge&apos;&gt;
        ///        &lt;meta name=&apos;viewport&apos; content=&apos;width=device-width, initial-scale=1.0&apos;&gt;
        ///        &lt;title&gt;Document&lt;/title&gt;
        ///        &lt;style&gt;
        ///            *{
        ///                box-sizing: border-box;
        ///                font-family: sans-serif;
        ///            }
        ///            body{
        ///                margin: 0;
        ///                display: flex;
        ///                flex-direction: column;
        ///       [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string EmailResetPassword_fr {
            get {
                return ResourceManager.GetString("EmailResetPassword.fr", resourceCulture);
            }
        }
    }
}
